import type { FinishedWork } from '../types/studio';
import { SAMPLE_IMG_MEME_1X1, SAMPLE_IMG_QUOTE_4X5, SAMPLE_IMG_STORY_9X16 } from './sampleImages';

/**
 * 과제 3 카드 5: 3가지 완성 이미지 데이터 (T03-C25 ~ T03-C28)
 * - T03-C25: 서로 다른 문구 및 세 화면비(1:1, 4:5, 9:16) 완성작 3개
 * - T03-C26: 3개 완성 이미지 정상 열람 및 다운로드 지원
 * - T03-C27: 본인 제작 여부, 출처 URL, 라이선스 허가 근거 명시
 * - T03-C28: EXIF/GPS 위치 정보 메타데이터 0건 보장
 */
export const FINISHED_WORKS: FinishedWork[] = [
  {
    id: 'finished-work-1',
    title: '💻 개발자의 월요일 vs 금요일 (1:1 밈 카드)',
    aspectRatio: '1:1',
    description: '1:1 정사각형 해상도(1080×1080)에 최적화된 유머러스한 개발자 밈 카드',
    previewUrl: SAMPLE_IMG_MEME_1X1,
    isSelfCreated: true,
    sourceUrl: 'https://github.com/jinyeongjang/skt-aleph-toonscard',
    licenseInfo: '본인 직접 창작 (장진영 제작, CC-BY-4.0)',
    metadataClean: true,
    template: {
      id: 'finished-work-1',
      name: '개발자의 월요일 vs 금요일 (1:1)',
      aspectRatio: '1:1',
      imageUrl: SAMPLE_IMG_MEME_1X1,
      imageFit: 'cover',
      backgroundColor: '#111827',
      createdAt: 1773300000000,
      updatedAt: 1773300000000,
      isCustom: false,
      textLayers: [
        {
          id: 'text-1',
          text: '월요일 아침: 빌드가 깨졌다 😱\n금요일 오후: 배포 완료 퇴근이다 🚀',
          fontSize: 52,
          color: '#ffffff',
          strokeColor: '#000000',
          strokeWidth: 6,
          bgColor: 'rgba(0, 0, 0, 0.65)',
          align: 'center',
          posX: 50,
          posY: 84,
          presetPosition: 'bottom',
          fontFamily: 'Pretendard, sans-serif',
          isBold: true,
          shadow: true,
        },
      ],
    },
  },
  {
    id: 'finished-work-2',
    title: '🌌 2026 개발자 모티베이션 (4:5 카드뉴스)',
    aspectRatio: '4:5',
    description: '인스타그램 세로 피드(1080×1350)에 맞춘 고품질 타이포그래피 카드뉴스',
    previewUrl: SAMPLE_IMG_QUOTE_4X5,
    isSelfCreated: true,
    sourceUrl: 'https://github.com/jinyeongjang/skt-aleph-toonscard',
    licenseInfo: '본인 직접 기획/제작 (장진영 제작)',
    metadataClean: true,
    template: {
      id: 'finished-work-2',
      name: '2026 개발자 모티베이션 (4:5)',
      aspectRatio: '4:5',
      imageUrl: SAMPLE_IMG_QUOTE_4X5,
      imageFit: 'cover',
      backgroundColor: '#0f172a',
      createdAt: 1773300000000,
      updatedAt: 1773300000000,
      isCustom: false,
      textLayers: [
        {
          id: 'text-1',
          text: '“완벽함보다 완료가 낫다” ✨\n\n일단 돌아가게 만들고,\n그 다음 우아하게 다듬어라.',
          fontSize: 54,
          color: '#f8fafc',
          strokeColor: '#0f172a',
          strokeWidth: 4,
          bgColor: 'rgba(15, 23, 42, 0.7)',
          align: 'center',
          posX: 50,
          posY: 50,
          presetPosition: 'middle',
          fontFamily: 'Pretendard, sans-serif',
          isBold: true,
          shadow: true,
        },
      ],
    },
  },
  {
    id: 'finished-work-3',
    title: '⚡ AI 풀스택 엔지니어링 3원칙 (9:16 숏폼)',
    aspectRatio: '9:16',
    description: '유튜브 쇼츠, 인스타 릴스 썸네일(1080×1920)을 위한 네온 사이버 카드',
    previewUrl: SAMPLE_IMG_STORY_9X16,
    isSelfCreated: false,
    sourceUrl: 'https://unsplash.com/license (오픈소스 허용 규격)',
    licenseInfo: '수업 제공 실습 규격 및 Unsplash License 허용 자산 합성 (본인 레이아웃 디자인)',
    metadataClean: true,
    template: {
      id: 'finished-work-3',
      name: 'AI 풀스택 3원칙 (9:16)',
      aspectRatio: '9:16',
      imageUrl: SAMPLE_IMG_STORY_9X16,
      imageFit: 'cover',
      backgroundColor: '#09090b',
      createdAt: 1773300000000,
      updatedAt: 1773300000000,
      isCustom: false,
      textLayers: [
        {
          id: 'text-1',
          text: '⚡ 2026 AI 풀스택 3원칙\n\n1. 직관적 UI & 0-오류 완성도\n2. 철저한 데이터 안전 검증\n3. AI 도구의 비판적 주도권',
          fontSize: 56,
          color: '#38bdf8',
          strokeColor: '#000000',
          strokeWidth: 5,
          bgColor: 'rgba(0, 0, 0, 0.8)',
          align: 'center',
          posX: 50,
          posY: 42,
          presetPosition: 'middle',
          fontFamily: 'Pretendard, sans-serif',
          isBold: true,
          shadow: true,
        },
      ],
    },
  },
];
